##' Given `train` and `test` data, generate map files for `couponId`,
##' `brand`, `categoryIDs`, `productGroup` and `userID`.
##' Map files contain two columns, with the first column the original
##' encrypted long characters and the second column integer numbers.
##'
##' @title Map generation function
##' @param trn train data path
##' @param tst test data path
##' @param path DIRECTORY where to generate the map files, default is
##' "./maps".
##' @return Five `.csv` files are generated under the `path` directory.
##' @examples
##' trn = read.table("../data/raw_data/DMC_2015_orders_train.txt",
##' stringsAsFactors=FALSE,sep ="|", header=TRUE)
##' tst = read.table("../data/raw_data/DMC_2015_orders_class.txt",
##' stringsAsFactors=FALSE,sep ="|", header=TRUE)
##' generateMaps(trn, tst)
##' @author Weicheng Zhu
generateMaps <- function(trn, tst, path="./maps"){
    couponid = unique(c(trn$couponID1, trn$couponID2, trn$couponID3,
        tst$couponID1, tst$couponID2, tst$couponID3))

    brand = unique(c(trn$brand1, trn$brand2, trn$brand3, tst$brand1,
        tst$brand2, tst$brand3))

    cat_tmp = c(trn$categoryIDs1, trn$categoryIDs2, trn$categoryIDs3,
        tst$categoryIDs1, tst$categoryIDs2, tst$categoryIDs3)
    
    catids = unique(unlist(lapply(cat_tmp, FUN = function(x)
        strsplit(x, split=",")[[1]])))

    progroup = unique(c(trn$productGroup1, trn$productGroup2,
        trn$productGroup3, tst$productGroup1, tst$productGroup2,
        tst$productGroup3))

    userid = unique(trn$userID, tst$userID)

    ## write variable maps to csv file
    wtcsv <- function(var, fname){
        write.csv(data.frame(var, label = 1:length(var)),
                  fname, row.names=FALSE, quote=FALSE)
    }
    wtcsv(couponid, file.path(path, "couponIdMap.csv"))
    wtcsv(brand, file.path(path,"brandMap.csv"))
    wtcsv(catids, file.path(path,"categoryIDsMap.csv"))
    wtcsv(progroup, file.path(path,"productGroupMap.csv"))
    wtcsv(userid, file.path(path,"userIdMap.csv"))
}


##' Recoding the long encrypted strings in the original data set to
##' corresponding map characters. (For present, the map files should
##' have the ordered integers starting from 1 as its second column,
##' which can be generated by generateMaps function.)
##'
##' @title Recoding the encrypted strings
##' @param infile input data frame
##' @param map.path path to the map files
##' @return recoded data frame
##' @examples
##' trn = read.table("../data/raw_data/DMC_2015_orders_train.txt",
##' stringsAsFactors=FALSE,sep ="|", header=TRUE)
##' tst = read.table("../data/raw_data/DMC_2015_orders_class.txt",
##' stringsAsFactors=FALSE,sep ="|", header=TRUE)
##' trn.simple = recode(trn)
##' tst.simple = recode(tst)
##' ## Write to csv file
##' write.csv(trn.simple, file = "./data/mc2015_train_simple.csv",
##' row.names=FALSE, quote=FALSE)
##' write.csv(tst.simple, file = "./data/mc2015_test_simple.csv",
##' row.names=FALSE, quote=FALSE)
##' @author Weicheng Zhu
recode <- function(infile, map.path="./maps"){
    ## load map files
    couponid.map = read.csv(file.path(map.path,"couponIdMap.csv"))[,1]
    brand.map = read.csv(file.path(map.path, "brandMap.csv"))[,1]
    category.map = read.csv(file.path(map.path, "categoryIDsMap.csv"))[,1]
    group.map = read.csv(file.path(map.path, "productGroupMap.csv"))[,1]
    userid.map = read.csv(file.path(map.path, "userIdMap.csv"))[,1]
    ## transform category from string to integers according to the map
    catTrans <- function(cat, map){
        catlist= lapply(cat, FUN = function(x) strsplit(x, split=",")[[1]])
        tmp = lapply(catlist, match, table=map)
        tmp = lapply(tmp, sort)
        res = sapply(tmp, paste0, collapse=":")
        res
    }
    infile = within(infile,{
        userID = match(infile$userID, userid.map)
        couponID1 = match(infile$couponID1, couponid.map)
        couponID2 = match(infile$couponID2, couponid.map)
        couponID3 = match(infile$couponID3, couponid.map)
        brand1 = match(infile$brand1, brand.map)
        brand2 = match(infile$brand2, brand.map)
        brand3 = match(infile$brand3, brand.map)
        productGroup1 = match(infile$productGroup1, group.map)
        productGroup2 = match(infile$productGroup2, group.map)
        productGroup3 = match(infile$productGroup3, group.map)
        categoryIDs1 = catTrans(infile$categoryIDs1, category.map)
        categoryIDs2 = catTrans(infile$categoryIDs2, category.map)
        categoryIDs3 = catTrans(infile$categoryIDs3, category.map)
    })
    infile
}
