To filter the feature matrix from set3_ver0.3 
========================================================

```{r}

Feature3 <- readRDS("~/dmc2015/featMat_based-on-HTVset3_LONG_ver0.3.rds")

w31 = Feature3[[1]]
w33 = Feature3[[3]]

cw31 = cbind(w31[[1]],w31[[2]])
cw33 = cbind(w33[[1]],w33[[2]])
########## the following is for safe check for categorical variables ###########
i = sapply(cw31, is.factor)
colnames(cw31)[i]
# we excluded the last three and included the first into model0 later
# [1] "order_match_class" "firstTimeCoup1Rec" "firstTimeCoup2Rec" "firstTimeCoup3Rec"


```

## Bad numbers (corresponding names) we excluded

```{r}

# badnum = -c(1,7,8,9,39:44, 50,   94:103,   476:937, 939:941)
# 
# [1] "orderID"                                             
# 
# [7] "firstTimeCoup1Rec"                                   "firstTimeCoup2Rec"                                  
# [9] "firstTimeCoup3Rec"                                                
# 
# [39] "time_lastVisit"                                      "avgTime_visit"                                      
# [41] "var_visit"                                           "medianTime_visit"                                   
# [43] "maxTime_visit"                                       "minTime_visit"                                      


# [49]                                                       "bPr2pr_approx_ratio" 
# 
# [93]                                                       "sim_ftd_invmax_cosSim_to1Col"                       
# [95] "sim_ftd_ivf_cosSim_to1Col"                           "sim_ftd_lnorm_cosSim_to1Col"                        
# [97] "sim_ftd_pif_cosSim_to1Col"                           "jaccard_to1Col"                                     
# [99] "sim_ftd_invmax_cosSim_mean"                          "sim_ftd_ivf_cosSim_mean"                            
# [101] "sim_ftd_lnorm_cosSim_mean"                           "sim_ftd_pif_cosSim_mean"                            
# [103] "sim_jaccard_mean" 
# 
# [475]                                                       "llr_est_basePrice_price_ratio"                      
# [477] "llr_naive_basePrice_price_ratio"                     "llr_est_basePriceXbasePrice_price_ratio"            
# [479] "llr_naive_basePriceXbasePrice_price_ratio"           "llr_est_brdXbasePrice_price_ratio"                  
# [481] "llr_naive_brdXbasePrice_price_ratio"                 "llr_est_brdXcatidsXbasePrice_price_ratio"           
# [483] "llr_naive_brdXcatidsXbasePrice_price_ratio"          "llr_est_brdXprodXbasePrice_price_ratio"             
# [485] "llr_naive_brdXprodXbasePrice_price_ratio"            "llr_est_rwdXbrdXbasePrice_price_ratio"              
# [487] "llr_naive_rwdXbrdXbasePrice_price_ratio"             "llr_est_catidsXbasePrice_price_ratio"               
# [489] "llr_naive_catidsXbasePrice_price_ratio"              "llr_est_rwdXcatidsXbasePrice_price_ratio"           
# [491] "llr_naive_rwdXcatidsXbasePrice_price_ratio"          "llr_est_EarlyRecXbasePrice_price_ratio"             
# [493] "llr_naive_EarlyRecXbasePrice_price_ratio"            "llr_est_brdXEarlyRecXbasePrice_price_ratio"         
# [495] "llr_naive_brdXEarlyRecXbasePrice_price_ratio"        "llr_est_catidsXEarlyRecXbasePrice_price_ratio"      
# [497] "llr_naive_catidsXEarlyRecXbasePrice_price_ratio"     "llr_est_luxXEarlyRecXbasePrice_price_ratio"         
# [499] "llr_naive_luxXEarlyRecXbasePrice_price_ratio"        "llr_est_prodXEarlyRecXbasePrice_price_ratio"        
# [501] "llr_naive_prodXEarlyRecXbasePrice_price_ratio"       "llr_est_rwdXEarlyRecXbasePrice_price_ratio"         
# [503] "llr_naive_rwdXEarlyRecXbasePrice_price_ratio"        "llr_est_luxXbasePrice_price_ratio"                  
# [505] "llr_naive_luxXbasePrice_price_ratio"                 "llr_est_luxXbrdXbasePrice_price_ratio"              
# [507] "llr_naive_luxXbrdXbasePrice_price_ratio"             "llr_est_luxXcatidsXbasePrice_price_ratio"           
# [509] "llr_naive_luxXcatidsXbasePrice_price_ratio"          "llr_est_luxXprodXbasePrice_price_ratio"             
# [511] "llr_naive_luxXprodXbasePrice_price_ratio"            "llr_est_rwdXluxXbasePrice_price_ratio"              
# [513] "llr_naive_rwdXluxXbasePrice_price_ratio"             "llr_est_priceXbasePrice_price_ratio"                
# [515] "llr_naive_priceXbasePrice_price_ratio"               "llr_est_prodXbasePrice_price_ratio"                 
# [517] "llr_naive_prodXbasePrice_price_ratio"                "llr_est_prodXcatidsXbasePrice_price_ratio"          
# [519] "llr_naive_prodXcatidsXbasePrice_price_ratio"         "llr_est_rwdXprodXbasePrice_price_ratio"             
# [521] "llr_naive_rwdXprodXbasePrice_price_ratio"            "llr_est_rwdXbasePrice_price_ratio"                  
# [523] "llr_naive_rwdXbasePrice_price_ratio"                 "llr_est_ShopFastXbasePrice_price_ratio"             
# [525] "llr_naive_ShopFastXbasePrice_price_ratio"            "llr_est_brdXShopFastXbasePrice_price_ratio"         
# [527] "llr_naive_brdXShopFastXbasePrice_price_ratio"        "llr_est_catidsXShopFastXbasePrice_price_ratio"      
# [529] "llr_naive_catidsXShopFastXbasePrice_price_ratio"     "llr_est_ShopFastXEarlyRecXbasePrice_price_ratio"    
# [531] "llr_naive_ShopFastXEarlyRecXbasePrice_price_ratio"   "llr_est_luxXShopFastXbasePrice_price_ratio"         
# [533] "llr_naive_luxXShopFastXbasePrice_price_ratio"        "llr_est_prodXShopFastXbasePrice_price_ratio"        
# [535] "llr_naive_prodXShopFastXbasePrice_price_ratio"       "llr_est_rwdXShopFastXbasePrice_price_ratio"         
# [537] "llr_naive_rwdXShopFastXbasePrice_price_ratio"        "llr_est_basePrice"                                  
# [539] "llr_naive_basePrice"                                 "llr_est_basePriceXbrd"                              
# [541] "llr_naive_basePriceXbrd"                             "llr_est_basePriceXbrdXcatids"                       
# [543] "llr_naive_basePriceXbrdXcatids"                      "llr_est_basePriceXbrdXprod"                         
# [545] "llr_naive_basePriceXbrdXprod"                        "llr_est_basePriceXrwdXbrd"                          
# [547] "llr_naive_basePriceXrwdXbrd"                         "llr_est_basePriceXcatids"                           
# [549] "llr_naive_basePriceXcatids"                          "llr_est_basePriceXrwdXcatids"                       
# [551] "llr_naive_basePriceXrwdXcatids"                      "llr_est_basePriceXEarlyRec"                         
# [553] "llr_naive_basePriceXEarlyRec"                        "llr_est_basePriceXbrdXEarlyRec"                     
# [555] "llr_naive_basePriceXbrdXEarlyRec"                    "llr_est_basePriceXcatidsXEarlyRec"                  
# [557] "llr_naive_basePriceXcatidsXEarlyRec"                 "llr_est_basePriceXluxXEarlyRec"                     
# [559] "llr_naive_basePriceXluxXEarlyRec"                    "llr_est_basePriceXprodXEarlyRec"                    
# [561] "llr_naive_basePriceXprodXEarlyRec"                   "llr_est_basePriceXrwdXEarlyRec"                     
# [563] "llr_naive_basePriceXrwdXEarlyRec"                    "llr_est_basePriceXlux"                              
# [565] "llr_naive_basePriceXlux"                             "llr_est_basePriceXluxXbrd"                          
# [567] "llr_naive_basePriceXluxXbrd"                         "llr_est_basePriceXluxXcatids"                       
# [569] "llr_naive_basePriceXluxXcatids"                      "llr_est_basePriceXluxXprod"                         
# [571] "llr_naive_basePriceXluxXprod"                        "llr_est_basePriceXrwdXlux"                          
# [573] "llr_naive_basePriceXrwdXlux"                         "llr_est_basePriceXprod"                             
# [575] "llr_naive_basePriceXprod"                            "llr_est_basePriceXprodXcatids"                      
# [577] "llr_naive_basePriceXprodXcatids"                     "llr_est_basePriceXrwdXprod"                         
# [579] "llr_naive_basePriceXrwdXprod"                        "llr_est_basePriceXrwd"                              
# [581] "llr_naive_basePriceXrwd"                             "llr_est_basePriceXShopFast"                         
# [583] "llr_naive_basePriceXShopFast"                        "llr_est_basePriceXbrdXShopFast"                     
# [585] "llr_naive_basePriceXbrdXShopFast"                    "llr_est_basePriceXcatidsXShopFast"                  
# [587] "llr_naive_basePriceXcatidsXShopFast"                 "llr_est_basePriceXShopFastXEarlyRec"                
# [589] "llr_naive_basePriceXShopFastXEarlyRec"               "llr_est_basePriceXluxXShopFast"                     
# [591] "llr_naive_basePriceXluxXShopFast"                    "llr_est_basePriceXprodXShopFast"                    
# [593] "llr_naive_basePriceXprodXShopFast"                   "llr_est_basePriceXrwdXShopFast"                     
# [595] "llr_naive_basePriceXrwdXShopFast"                    "llr_est_brd"                                        
# [597] "llr_naive_brd"                                       "llr_est_basePriceXbrdXbasePrice_price_ratio"        
# [599] "llr_naive_basePriceXbrdXbasePrice_price_ratio"       "llr_est_priceXbrdXbasePrice_price_ratio"            
# [601] "llr_naive_priceXbrdXbasePrice_price_ratio"           "llr_est_brdXcatids"                                 
# [603] "llr_naive_brdXcatids"                                "llr_est_rwdXbrdXcatids"                             
# [605] "llr_naive_rwdXbrdXcatids"                            "llr_est_brdXprod"                                   
# [607] "llr_naive_brdXprod"                                  "llr_est_brdXprodXcatids"                            
# [609] "llr_naive_brdXprodXcatids"                           "llr_est_rwdXbrdXprodXcatids"                        
# [611] "llr_naive_rwdXbrdXprodXcatids"                       "llr_est_rwdXbrdXprod"                               
# [613] "llr_naive_rwdXbrdXprod"                              "llr_est_rwdXbrd"                                    
# [615] "llr_naive_rwdXbrd"                                   "llr_est_catids"                                     
# [617] "llr_naive_catids"                                    "llr_est_basePriceXcatidsXbasePrice_price_ratio"     
# [619] "llr_naive_basePriceXcatidsXbasePrice_price_ratio"    "llr_est_priceXcatidsXbasePrice_price_ratio"         
# [621] "llr_naive_priceXcatidsXbasePrice_price_ratio"        "llr_est_rwdXcatids"                                 
# [623] "llr_naive_rwdXcatids"                                "llr_est_cpn"                                        
# [625] "llr_naive_cpn"                                       "llr_est_cpnXEarlyRec"                               
# [627] "llr_naive_cpnXEarlyRec"                              "llr_est_cpnXShopFast"                               
# [629] "llr_naive_cpnXShopFast"                              "llr_est_EarlyRec"                                   
# [631] "llr_naive_EarlyRec"                                  "llr_est_basePriceXEarlyRecXbasePrice_price_ratio"   
# [633] "llr_naive_basePriceXEarlyRecXbasePrice_price_ratio"  "llr_est_priceXEarlyRecXbasePrice_price_ratio"       
# [635] "llr_naive_priceXEarlyRecXbasePrice_price_ratio"      "llr_est_brdXEarlyRec"                               
# [637] "llr_naive_brdXEarlyRec"                              "llr_est_brdXcatidsXEarlyRec"                        
# [639] "llr_naive_brdXcatidsXEarlyRec"                       "llr_est_rwdXbrdXcatidsXEarlyRec"                    
# [641] "llr_naive_rwdXbrdXcatidsXEarlyRec"                   "llr_est_brdXprodXEarlyRec"                          
# [643] "llr_naive_brdXprodXEarlyRec"                         "llr_est_brdXprodXcatidsXEarlyRec"                   
# [645] "llr_naive_brdXprodXcatidsXEarlyRec"                  "llr_est_rwdXbrdXprodXcatidsXEarlyRec"               
# [647] "llr_naive_rwdXbrdXprodXcatidsXEarlyRec"              "llr_est_rwdXbrdXprodXEarlyRec"                      
# [649] "llr_naive_rwdXbrdXprodXEarlyRec"                     "llr_est_rwdXbrdXEarlyRec"                           
# [651] "llr_naive_rwdXbrdXEarlyRec"                          "llr_est_catidsXEarlyRec"                            
# [653] "llr_naive_catidsXEarlyRec"                           "llr_est_rwdXcatidsXEarlyRec"                        
# [655] "llr_naive_rwdXcatidsXEarlyRec"                       "llr_est_luxXEarlyRec"                               
# [657] "llr_naive_luxXEarlyRec"                              "llr_est_luxXbrdXEarlyRec"                           
# [659] "llr_naive_luxXbrdXEarlyRec"                          "llr_est_luxXbrdXcatidsXEarlyRec"                    
# [661] "llr_naive_luxXbrdXcatidsXEarlyRec"                   "llr_est_rwdXluxXbrdXcatidsXEarlyRec"                
# [663] "llr_naive_rwdXluxXbrdXcatidsXEarlyRec"               "llr_est_luxXbrdXprodXEarlyRec"                      
# [665] "llr_naive_luxXbrdXprodXEarlyRec"                     "llr_est_luxXbrdXprodXcatidsXEarlyRec"               
# [667] "llr_naive_luxXbrdXprodXcatidsXEarlyRec"              "llr_est_rwdXluxXbrdXprodXEarlyRec"                  
# [669] "llr_naive_rwdXluxXbrdXprodXEarlyRec"                 "llr_est_rwdXluxXbrdXEarlyRec"                       
# [671] "llr_naive_rwdXluxXbrdXEarlyRec"                      "llr_est_luxXcatidsXEarlyRec"                        
# [673] "llr_naive_luxXcatidsXEarlyRec"                       "llr_est_rwdXluxXcatidsXEarlyRec"                    
# [675] "llr_naive_rwdXluxXcatidsXEarlyRec"                   "llr_est_luxXprodXEarlyRec"                          
# [677] "llr_naive_luxXprodXEarlyRec"                         "llr_est_luxXprodXcatidsXEarlyRec"                   
# [679] "llr_naive_luxXprodXcatidsXEarlyRec"                  "llr_est_rwdXluxXprodXcatidsXEarlyRec"               
# [681] "llr_naive_rwdXluxXprodXcatidsXEarlyRec"              "llr_est_rwdXluxXprodXEarlyRec"                      
# [683] "llr_naive_rwdXluxXprodXEarlyRec"                     "llr_est_rwdXluxXEarlyRec"                           
# [685] "llr_naive_rwdXluxXEarlyRec"                          "llr_est_prodXEarlyRec"                              
# [687] "llr_naive_prodXEarlyRec"                             "llr_est_prodXcatidsXEarlyRec"                       
# [689] "llr_naive_prodXcatidsXEarlyRec"                      "llr_est_rwdXprodXcatidsXEarlyRec"                   
# [691] "llr_naive_rwdXprodXcatidsXEarlyRec"                  "llr_est_rwdXprodXEarlyRec"                          
# [693] "llr_naive_rwdXprodXEarlyRec"                         "llr_est_rwdXEarlyRec"                               
# [695] "llr_naive_rwdXEarlyRec"                              "llr_est_OrderExpire60"                              
# [697] "llr_naive_OrderExpire60"                             "llr_est_lux"                                        
# [699] "llr_naive_lux"                                       "llr_est_basePriceXluxXbasePrice_price_ratio"        
# [701] "llr_naive_basePriceXluxXbasePrice_price_ratio"       "llr_est_priceXluxXbasePrice_price_ratio"            
# [703] "llr_naive_priceXluxXbasePrice_price_ratio"           "llr_est_luxXbrd"                                    
# [705] "llr_naive_luxXbrd"                                   "llr_est_luxXbrdXcatids"                             
# [707] "llr_naive_luxXbrdXcatids"                            "llr_est_rwdXluxXbrdXcatids"                         
# [709] "llr_naive_rwdXluxXbrdXcatids"                        "llr_est_luxXbrdXprod"                               
# [711] "llr_naive_luxXbrdXprod"                              "llr_est_luxXbrdXprodXcatids"                        
# [713] "llr_naive_luxXbrdXprodXcatids"                       "llr_est_rwdXluxXbrdXprodXcatids"                    
# [715] "llr_naive_rwdXluxXbrdXprodXcatids"                   "llr_est_rwdXluxXbrdXprod"                           
# [717] "llr_naive_rwdXluxXbrdXprod"                          "llr_est_rwdXluxXbrd"                                
# [719] "llr_naive_rwdXluxXbrd"                               "llr_est_luxXcatids"                                 
# [721] "llr_naive_luxXcatids"                                "llr_est_rwdXluxXcatids"                             
# [723] "llr_naive_rwdXluxXcatids"                            "llr_est_luxXprod"                                   
# [725] "llr_naive_luxXprod"                                  "llr_est_luxXprodXcatids"                            
# [727] "llr_naive_luxXprodXcatids"                           "llr_est_rwdXluxXprodXcatids"                        
# [729] "llr_naive_rwdXluxXprodXcatids"                       "llr_est_rwdXluxXprod"                               
# [731] "llr_naive_rwdXluxXprod"                              "llr_est_rwdXlux"                                    
# [733] "llr_naive_rwdXlux"                                   "llr_est_price"                                      
# [735] "llr_naive_price"                                     "llr_est_priceXbrd"                                  
# [737] "llr_naive_priceXbrd"                                 "llr_est_priceXbrdXcatids"                           
# [739] "llr_naive_priceXbrdXcatids"                          "llr_est_priceXbrdXprod"                             
# [741] "llr_naive_priceXbrdXprod"                            "llr_est_priceXrwdXbrd"                              
# [743] "llr_naive_priceXrwdXbrd"                             "llr_est_priceXcatids"                               
# [745] "llr_naive_priceXcatids"                              "llr_est_priceXrwdXcatids"                           
# [747] "llr_naive_priceXrwdXcatids"                          "llr_est_priceXEarlyRec"                             
# [749] "llr_naive_priceXEarlyRec"                            "llr_est_priceXbrdXEarlyRec"                         
# [751] "llr_naive_priceXbrdXEarlyRec"                        "llr_est_priceXcatidsXEarlyRec"                      
# [753] "llr_naive_priceXcatidsXEarlyRec"                     "llr_est_priceXluxXEarlyRec"                         
# [755] "llr_naive_priceXluxXEarlyRec"                        "llr_est_priceXprodXEarlyRec"                        
# [757] "llr_naive_priceXprodXEarlyRec"                       "llr_est_priceXrwdXEarlyRec"                         
# [759] "llr_naive_priceXrwdXEarlyRec"                        "llr_est_priceXlux"                                  
# [761] "llr_naive_priceXlux"                                 "llr_est_priceXluxXbrd"                              
# [763] "llr_naive_priceXluxXbrd"                             "llr_est_priceXluxXcatids"                           
# [765] "llr_naive_priceXluxXcatids"                          "llr_est_priceXluxXprod"                             
# [767] "llr_naive_priceXluxXprod"                            "llr_est_priceXrwdXlux"                              
# [769] "llr_naive_priceXrwdXlux"                             "llr_est_priceXprod"                                 
# [771] "llr_naive_priceXprod"                                "llr_est_priceXprodXcatids"                          
# [773] "llr_naive_priceXprodXcatids"                         "llr_est_priceXrwdXprod"                             
# [775] "llr_naive_priceXrwdXprod"                            "llr_est_priceXrwd"                                  
# [777] "llr_naive_priceXrwd"                                 "llr_est_priceXShopFast"                             
# [779] "llr_naive_priceXShopFast"                            "llr_est_priceXbrdXShopFast"                         
# [781] "llr_naive_priceXbrdXShopFast"                        "llr_est_priceXcatidsXShopFast"                      
# [783] "llr_naive_priceXcatidsXShopFast"                     "llr_est_priceXShopFastXEarlyRec"                    
# [785] "llr_naive_priceXShopFastXEarlyRec"                   "llr_est_priceXluxXShopFast"                         
# [787] "llr_naive_priceXluxXShopFast"                        "llr_est_priceXprodXShopFast"                        
# [789] "llr_naive_priceXprodXShopFast"                       "llr_est_priceXrwdXShopFast"                         
# [791] "llr_naive_priceXrwdXShopFast"                        "llr_est_prod"                                       
# [793] "llr_naive_prod"                                      "llr_est_basePriceXprodXbasePrice_price_ratio"       
# [795] "llr_naive_basePriceXprodXbasePrice_price_ratio"      "llr_est_priceXprodXbasePrice_price_ratio"           
# [797] "llr_naive_priceXprodXbasePrice_price_ratio"          "llr_est_prodXcatids"                                
# [799] "llr_naive_prodXcatids"                               "llr_est_rwdXprodXcatids"                            
# [801] "llr_naive_rwdXprodXcatids"                           "llr_est_rwdXprod"                                   
# [803] "llr_naive_rwdXprod"                                  "llr_est_RecExpire60"                                
# [805] "llr_naive_RecExpire60"                               "llr_est_RecOrder60"                                 
# [807] "llr_naive_RecOrder60"                                "llr_est_rwd"                                        
# [809] "llr_naive_rwd"                                       "llr_est_basePriceXrwdXbasePrice_price_ratio"        
# [811] "llr_naive_basePriceXrwdXbasePrice_price_ratio"       "llr_est_priceXrwdXbasePrice_price_ratio"            
# [813] "llr_naive_priceXrwdXbasePrice_price_ratio"           "llr_est_Shop15"                                     
# [815] "llr_naive_Shop15"                                    "llr_est_Shop30"                                     
# [817] "llr_naive_Shop30"                                    "llr_est_Shop60"                                     
# [819] "llr_naive_Shop60"                                    "llr_est_ShopFast"                                   
# [821] "llr_naive_ShopFast"                                  "llr_est_basePriceXShopFastXbasePrice_price_ratio"   
# [823] "llr_naive_basePriceXShopFastXbasePrice_price_ratio"  "llr_est_priceXShopFastXbasePrice_price_ratio"       
# [825] "llr_naive_priceXShopFastXbasePrice_price_ratio"      "llr_est_brdXShopFast"                               
# [827] "llr_naive_brdXShopFast"                              "llr_est_brdXcatidsXShopFast"                        
# [829] "llr_naive_brdXcatidsXShopFast"                       "llr_est_rwdXbrdXcatidsXShopFast"                    
# [831] "llr_naive_rwdXbrdXcatidsXShopFast"                   "llr_est_brdXprodXShopFast"                          
# [833] "llr_naive_brdXprodXShopFast"                         "llr_est_brdXprodXcatidsXShopFast"                   
# [835] "llr_naive_brdXprodXcatidsXShopFast"                  "llr_est_rwdXbrdXprodXcatidsXShopFast"               
# [837] "llr_naive_rwdXbrdXprodXcatidsXShopFast"              "llr_est_rwdXbrdXprodXShopFast"                      
# [839] "llr_naive_rwdXbrdXprodXShopFast"                     "llr_est_rwdXbrdXShopFast"                           
# [841] "llr_naive_rwdXbrdXShopFast"                          "llr_est_catidsXShopFast"                            
# [843] "llr_naive_catidsXShopFast"                           "llr_est_rwdXcatidsXShopFast"                        
# [845] "llr_naive_rwdXcatidsXShopFast"                       "llr_est_ShopFastXEarlyRec"                          
# [847] "llr_naive_ShopFastXEarlyRec"                         "llr_est_brdXShopFastXEarlyRec"                      
# [849] "llr_naive_brdXShopFastXEarlyRec"                     "llr_est_brdXcatidsXShopFastXEarlyRec"               
# [851] "llr_naive_brdXcatidsXShopFastXEarlyRec"              "llr_est_rwdXbrdXcatidsXShopFastXEarlyRec"           
# [853] "llr_naive_rwdXbrdXcatidsXShopFastXEarlyRec"          "llr_est_brdXprodXShopFastXEarlyRec"                 
# [855] "llr_naive_brdXprodXShopFastXEarlyRec"                "llr_est_brdXprodXcatidsXShopFastXEarlyRec"          
# [857] "llr_naive_brdXprodXcatidsXShopFastXEarlyRec"         "llr_est_rwdXbrdXprodXShopFastXEarlyRec"             
# [859] "llr_naive_rwdXbrdXprodXShopFastXEarlyRec"            "llr_est_rwdXbrdXShopFastXEarlyRec"                  
# [861] "llr_naive_rwdXbrdXShopFastXEarlyRec"                 "llr_est_catidsXShopFastXEarlyRec"                   
# [863] "llr_naive_catidsXShopFastXEarlyRec"                  "llr_est_rwdXcatidsXShopFastXEarlyRec"               
# [865] "llr_naive_rwdXcatidsXShopFastXEarlyRec"              "llr_est_luxXShopFastXEarlyRec"                      
# [867] "llr_naive_luxXShopFastXEarlyRec"                     "llr_est_luxXbrdXShopFastXEarlyRec"                  
# [869] "llr_naive_luxXbrdXShopFastXEarlyRec"                 "llr_est_luxXbrdXcatidsXShopFastXEarlyRec"           
# [871] "llr_naive_luxXbrdXcatidsXShopFastXEarlyRec"          "llr_est_luxXbrdXprodXShopFastXEarlyRec"             
# [873] "llr_naive_luxXbrdXprodXShopFastXEarlyRec"            "llr_est_rwdXluxXbrdXShopFastXEarlyRec"              
# [875] "llr_naive_rwdXluxXbrdXShopFastXEarlyRec"             "llr_est_luxXcatidsXShopFastXEarlyRec"               
# [877] "llr_naive_luxXcatidsXShopFastXEarlyRec"              "llr_est_rwdXluxXcatidsXShopFastXEarlyRec"           
# [879] "llr_naive_rwdXluxXcatidsXShopFastXEarlyRec"          "llr_est_luxXprodXShopFastXEarlyRec"                 
# [881] "llr_naive_luxXprodXShopFastXEarlyRec"                "llr_est_luxXprodXcatidsXShopFastXEarlyRec"          
# [883] "llr_naive_luxXprodXcatidsXShopFastXEarlyRec"         "llr_est_rwdXluxXprodXShopFastXEarlyRec"             
# [885] "llr_naive_rwdXluxXprodXShopFastXEarlyRec"            "llr_est_rwdXluxXShopFastXEarlyRec"                  
# [887] "llr_naive_rwdXluxXShopFastXEarlyRec"                 "llr_est_prodXShopFastXEarlyRec"                     
# [889] "llr_naive_prodXShopFastXEarlyRec"                    "llr_est_prodXcatidsXShopFastXEarlyRec"              
# [891] "llr_naive_prodXcatidsXShopFastXEarlyRec"             "llr_est_rwdXprodXcatidsXShopFastXEarlyRec"          
# [893] "llr_naive_rwdXprodXcatidsXShopFastXEarlyRec"         "llr_est_rwdXprodXShopFastXEarlyRec"                 
# [895] "llr_naive_rwdXprodXShopFastXEarlyRec"                "llr_est_rwdXShopFastXEarlyRec"                      
# [897] "llr_naive_rwdXShopFastXEarlyRec"                     "llr_est_luxXShopFast"                               
# [899] "llr_naive_luxXShopFast"                              "llr_est_luxXbrdXShopFast"                           
# [901] "llr_naive_luxXbrdXShopFast"                          "llr_est_luxXbrdXcatidsXShopFast"                    
# [903] "llr_naive_luxXbrdXcatidsXShopFast"                   "llr_est_rwdXluxXbrdXcatidsXShopFast"                
# [905] "llr_naive_rwdXluxXbrdXcatidsXShopFast"               "llr_est_luxXbrdXprodXShopFast"                      
# [907] "llr_naive_luxXbrdXprodXShopFast"                     "llr_est_luxXbrdXprodXcatidsXShopFast"               
# [909] "llr_naive_luxXbrdXprodXcatidsXShopFast"              "llr_est_rwdXluxXbrdXprodXShopFast"                  
# [911] "llr_naive_rwdXluxXbrdXprodXShopFast"                 "llr_est_rwdXluxXbrdXShopFast"                       
# [913] "llr_naive_rwdXluxXbrdXShopFast"                      "llr_est_luxXcatidsXShopFast"                        
# [915] "llr_naive_luxXcatidsXShopFast"                       "llr_est_rwdXluxXcatidsXShopFast"                    
# [917] "llr_naive_rwdXluxXcatidsXShopFast"                   "llr_est_luxXprodXShopFast"                          
# [919] "llr_naive_luxXprodXShopFast"                         "llr_est_luxXprodXcatidsXShopFast"                   
# [921] "llr_naive_luxXprodXcatidsXShopFast"                  "llr_est_rwdXluxXprodXcatidsXShopFast"               
# [923] "llr_naive_rwdXluxXprodXcatidsXShopFast"              "llr_est_rwdXluxXprodXShopFast"                      
# [925] "llr_naive_rwdXluxXprodXShopFast"                     "llr_est_rwdXluxXShopFast"                           
# [927] "llr_naive_rwdXluxXShopFast"                          "llr_est_prodXShopFast"                              
# [929] "llr_naive_prodXShopFast"                             "llr_est_prodXcatidsXShopFast"                       
# [931] "llr_naive_prodXcatidsXShopFast"                      "llr_est_rwdXprodXcatidsXShopFast"                   
# [933] "llr_naive_rwdXprodXcatidsXShopFast"                  "llr_est_rwdXprodXShopFast"                          
# [935] "llr_naive_rwdXprodXShopFast"                         "llr_est_rwdXShopFast"                               
# [937] "llr_naive_rwdXShopFast"                              
# 
```

## Good numbers that we included as base model: model0

```{r}
#######################

# model0_colnames_num = c(2,3,10,31,47,48,49,87,88,89,90)
# 
# [1]                                                        "couponCol"     
# [3] "order_match_class"                                        
# [9]                                                        "n.usr"                
# [31] "order.early"               
# [47] "batch_visits"                                        "batch_visitOrder" 
# [49] "bPr2pr_ratio"                                          
# [87] "nCoupon"                                             "ntimesCol1"                                         
# [89] "ntimesCol2"                                          "ntimesCol3"      


```

## Random columnns those will enter our model by forward selection

```{r}
######################## random numbers #################

# ran_num = seq(941)[-c(2,3,10,31,49,87,88,89,90,1,7,8,9,50,94:103,476:937)]
# sort(ran_num)
# 
# 4 5 6  
# 11:30
# 32:38
# 45:48
# 51:86  
# 91:93 
# 104:475 
# 938
# 
# 
# > names(cw31)[sort(ran_num)]
# the following names are right, the front index is right, from 104 to 475 the showing index is wrong, but # it does not matter

# [3]                                                        "nCoup1Batch"                                                                                 
# [5]  "nCoup2Batch"                                         "nCoup3Batch"                                         

# [10]                                                       "TimeBtwnSentRec.mean"                               
# [12] "TimeBtwnSentRec.max"                                 "TimeBtwnSentRec.min"                                
# [14] "TimeBtwnSentRec.median"                              "TimeBtwnRecExpire.mean"                             
# [16] "TimeBtwnRecExpire.max"                               "TimeBtwnRecExpire.min"                              
# [18] "TimeBtwnRecExpire.median"                            "TimeBtwnRecOrder.mean"                              
# [20] "TimeBtwnRecOrder.max"                                "TimeBtwnRecOrder.min"                               
# [22] "TimeBtwnRecOrder.median"                             "TimeBtwnOrderExpire.mean"                           
# [24] "TimeBtwnOrderExpire.max"                             "TimeBtwnOrderExpire.min"                            
# [26] "TimeBtwnOrderExpire.median"                          "order.weekend"                                      
# [28] "order.FriSat"                                        "order.weekday"                                      
# [30] "order.worktime"                                      
# 
# [31]                                                       "couponRec.weekend"                                  
# [33] "couponRec.FriSat"                                    "couponRec.weekday"                                  
# [35] "orderMaxPerWeek"                                     "orderMinPerWeek"                                    
# [37] "ActiveWeek"                                          "tot_visitOrder"                                     
                                      
# [45] "avgTime_recd_order"                                  "avgTime_order" 
# [47] "batch_visits"                                        "batch_visitOrder"                                   

# [51] "sim_ftd_invmax_cosSim_to2Col"                        "sim_ftd_invmax_cosSim_to3Col"                       
# [53] "sim_ftd_ivf_cosSim_to2Col"                           "sim_ftd_ivf_cosSim_to3Col"                          
# [55] "sim_ftd_lnorm_cosSim_to2Col"                         "sim_ftd_lnorm_cosSim_to3Col"                        
# [57] "sim_ftd_pif_cosSim_to2Col"                           "sim_ftd_pif_cosSim_to3Col"                          
# [59] "brand3_or_not"                                       "item_premium_version"                               
# [61] "item_price_max"                                      "item_price_min"                                     
# [63] "item_price_num"                                      "item_zprice_unique"                                 
# [65] "item_zprice_orig"                                    "item_zprice_unscale"                                
# [67] "item_price_max_scale"                                "item_basePrice_max"                                 
# [69] "item_basePrice_min"                                  "item_basePrice_num"                                 
# [71] "item_zbasePrice_unique"                              "item_zbasePrice_orig"                               
# [73] "item_zbasePrice_unscale"                             "item_basePrice_max_scale"                           
# [75] "item_reward_max"                                     "item_reward_min"                                    
# [77] "item_reward_num"                                     "item_zreward_unique"                                
# [79] "item_zreward_orig"                                   "item_zreward_unscale"                               
# [81] "item_reward_max_scale"                               "item_zbp_zp_ratio_unique"                           
# [83] "item_zbp_zp_ratio_orig"                              "item_zbp_zp_ratio_unscale"                          
# [85] "jaccard_to2Col"                                      "jaccard_to3Col"                                     

# [91] "ptimesCol1"                                          "ptimesCol2"                                         
# [93] "ptimesCol3"                                          

# [103]                                                      "basePrice_brand_nUser"                              
# [105] "basePrice_brand_nUserUsed"                           "basePrice_brand_prob"                               
# [107] "basePrice_brand_Twice"                               "basePrice_categoryIDs_nUser"                        
# [109] "basePrice_categoryIDs_nUserUsed"                     "basePrice_categoryIDs_prob"                         
# [111] "basePrice_categoryIDs_Twice"                         "basePrice_nUser"                                    
# [113] "basePrice_nUserUsed"                                 "basePrice_premiumProduct_nUser"                     
# [115] "basePrice_premiumProduct_nUserUsed"                  "basePrice_premiumProduct_prob"                      
# [117] "basePrice_premiumProduct_Twice"                      "basePrice_prob"                                     
# [119] "basePrice_productGroup_nUser"                        "basePrice_productGroup_nUserUsed"                   
# [121] "basePrice_productGroup_prob"                         "basePrice_productGroup_Twice"                       
# [123] "basePrice_ratio_bp_p_round_nUser"                    "basePrice_ratio_bp_p_round_nUserUsed"               
# [125] "basePrice_ratio_bp_p_round_prob"                     "basePrice_ratio_bp_p_round_Twice"                   
# [127] "basePrice_Twice"                                     "brand_premiumProduct_nUser"                         
# [129] "brand_premiumProduct_nUserUsed"                      "brand_premiumProduct_prob"                          
# [131] "brand_premiumProduct_Twice"                          "categoryIDs_brand_nUser"                            
# [133] "categoryIDs_brand_nUserUsed"                         "categoryIDs_brand_prob"                             
# [135] "categoryIDs_brand_Twice"                             "categoryIDs_nUser"                                  
# [137] "categoryIDs_nUserUsed"                               "categoryIDs_premiumProduct_nUser"                   
# [139] "categoryIDs_premiumProduct_nUserUsed"                "categoryIDs_premiumProduct_prob"                    
# [141] "categoryIDs_premiumProduct_Twice"                    "categoryIDs_prob"                                   
# [143] "categoryIDs_ratio_bp_p_round_nUser"                  "categoryIDs_ratio_bp_p_round_nUserUsed"             
# [145] "categoryIDs_ratio_bp_p_round_prob"                   "categoryIDs_ratio_bp_p_round_Twice"                 
# [147] "categoryIDs_Twice"                                   "couponID_couponsReceivedDoW_nUser"                  
# [149] "couponID_couponsReceivedDoW_nUserUsed"               "couponID_couponsReceivedDoW_prob"                   
# [151] "couponID_couponsReceivedDoW_Twice"                   "couponID_couponsReceivedTime_nUser"                 
# [153] "couponID_couponsReceivedTime_nUserUsed"              "couponID_couponsReceivedTime_prob"                  
# [155] "couponID_couponsReceivedTime_Twice"                  "couponID_nUser"                                     
# [157] "couponID_nUserUsed"                                  "couponID_orderTimeDoW_nUser"                        
# [159] "couponID_orderTimeDoW_nUserUsed"                     "couponID_orderTimeDoW_prob"                         
# [161] "couponID_orderTimeDoW_Twice"                         "couponID_orderTimeTime_nUser"                       
# [163] "couponID_orderTimeTime_nUserUsed"                    "couponID_orderTimeTime_prob"                        
# [165] "couponID_prob"                                       "couponID_TimeBtwnRecOrder_disc_nUser"               
# [167] "couponID_TimeBtwnRecOrder_disc_nUserUsed"            "couponID_TimeBtwnRecOrder_disc_prob"                
# [169] "couponID_TimeBtwnRecOrder_disc_Twice"                "couponID_Twice"                                     
# [171] "couponsReceivedDoW_basePrice_nUser"                  "couponsReceivedDoW_basePrice_nUserUsed"             
# [173] "couponsReceivedDoW_basePrice_prob"                   "couponsReceivedDoW_basePrice_Twice"                 
# [175] "couponsReceivedDoW_brand_nUser"                      "couponsReceivedDoW_brand_nUserUsed"                 
# [177] "couponsReceivedDoW_brand_prob"                       "couponsReceivedDoW_brand_Twice"                     
# [179] "couponsReceivedDoW_categoryIDs_nUser"                "couponsReceivedDoW_categoryIDs_nUserUsed"           
# [181] "couponsReceivedDoW_categoryIDs_prob"                 "couponsReceivedDoW_categoryIDs_Twice"               
# [183] "couponsReceivedDoW_nUser"                            "couponsReceivedDoW_nUserUsed"                       
# [185] "couponsReceivedDoW_orderTimeDoW_nUser"               "couponsReceivedDoW_orderTimeDoW_nUserUsed"          
# [187] "couponsReceivedDoW_orderTimeDoW_prob"                "couponsReceivedDoW_orderTimeDoW_Twice"              
# [189] "couponsReceivedDoW_orderTimeTime_nUser"              "couponsReceivedDoW_orderTimeTime_nUserUsed"         
# [191] "couponsReceivedDoW_orderTimeTime_prob"               "couponsReceivedDoW_orderTimeTime_Twice"             
# [193] "couponsReceivedDoW_premiumProduct_nUser"             "couponsReceivedDoW_premiumProduct_nUserUsed"      
# [171] "couponsReceivedDoW_premiumProduct_prob"              "couponsReceivedDoW_price_nUser"                     
# [173] "couponsReceivedDoW_price_nUserUsed"                  "couponsReceivedDoW_price_prob"                      
# [175] "couponsReceivedDoW_price_Twice"                      "couponsReceivedDoW_prob"                            
# [177] "couponsReceivedDoW_productGroup_nUser"               "couponsReceivedDoW_productGroup_nUserUsed"          
# [179] "couponsReceivedDoW_productGroup_prob"                "couponsReceivedDoW_productGroup_Twice"              
# [181] "couponsReceivedDoW_ratio_bp_p_round_nUser"           "couponsReceivedDoW_ratio_bp_p_round_nUserUsed"      
# [183] "couponsReceivedDoW_ratio_bp_p_round_prob"            "couponsReceivedDoW_ratio_bp_p_round_Twice"          
# [185] "couponsReceivedDoW_TimeBtwnRecOrder_disc_nUser"      "couponsReceivedDoW_TimeBtwnRecOrder_disc_nUserUsed" 
# [187] "couponsReceivedDoW_TimeBtwnRecOrder_disc_prob"       "couponsReceivedDoW_TimeBtwnRecOrder_disc_Twice"     
# [189] "couponsReceivedTime_basePrice_nUser"                 "couponsReceivedTime_basePrice_nUserUsed"            
# [191] "couponsReceivedTime_basePrice_prob"                  "couponsReceivedTime_basePrice_Twice"                
# [193] "couponsReceivedTime_brand_nUser"                     "couponsReceivedTime_brand_nUserUsed"                
# [195] "couponsReceivedTime_brand_prob"                      "couponsReceivedTime_brand_Twice"                    
# [197] "couponsReceivedTime_categoryIDs_nUser"               "couponsReceivedTime_categoryIDs_nUserUsed"          
# [199] "couponsReceivedTime_categoryIDs_prob"                "couponsReceivedTime_categoryIDs_Twice"              
# [201] "couponsReceivedTime_couponsReceivedDoW_nUser"        "couponsReceivedTime_couponsReceivedDoW_nUserUsed"   
# [203] "couponsReceivedTime_couponsReceivedDoW_prob"         "couponsReceivedTime_couponsReceivedDoW_Twice"       
# [205] "couponsReceivedTime_nUser"                           "couponsReceivedTime_nUserUsed"                      
# [207] "couponsReceivedTime_orderTimeDoW_nUser"              "couponsReceivedTime_orderTimeDoW_nUserUsed"         
# [209] "couponsReceivedTime_orderTimeDoW_prob"               "couponsReceivedTime_orderTimeDoW_Twice"             
# [211] "couponsReceivedTime_orderTimeTime_nUserUsed"         "couponsReceivedTime_orderTimeTime_prob"             
# [213] "couponsReceivedTime_orderTimeTime_Twice"             "couponsReceivedTime_premiumProduct_nUser"           
# [215] "couponsReceivedTime_premiumProduct_nUserUsed"        "couponsReceivedTime_premiumProduct_prob"            
# [217] "couponsReceivedTime_premiumProduct_Twice"            "couponsReceivedTime_price_nUser"                    
# [219] "couponsReceivedTime_price_nUserUsed"                 "couponsReceivedTime_price_prob"                     
# [221] "couponsReceivedTime_price_Twice"                     "couponsReceivedTime_prob"                           
# [223] "couponsReceivedTime_productGroup_nUser"              "couponsReceivedTime_productGroup_nUserUsed"         
# [225] "couponsReceivedTime_productGroup_prob"               "couponsReceivedTime_productGroup_Twice"             
# [227] "couponsReceivedTime_ratio_bp_p_round_nUser"          "couponsReceivedTime_ratio_bp_p_round_nUserUsed"     
# [229] "couponsReceivedTime_ratio_bp_p_round_prob"           "couponsReceivedTime_ratio_bp_p_round_Twice"         
# [231] "couponsReceivedTime_TimeBtwnRecOrder_disc_nUser"     "couponsReceivedTime_TimeBtwnRecOrder_disc_nUserUsed"
# [233] "couponsReceivedTime_TimeBtwnRecOrder_disc_prob"      "couponsReceivedTime_TimeBtwnRecOrder_disc_Twice"    
# [235] "couponsReceivedTime_Twice"                           "orderTimeDoW_basePrice_nUser"                       
# [237] "orderTimeDoW_basePrice_nUserUsed"                    "orderTimeDoW_basePrice_prob"                        
# [239] "orderTimeDoW_basePrice_Twice"                        "orderTimeDoW_brand_nUser"                           
# [241] "orderTimeDoW_brand_nUserUsed"                        "orderTimeDoW_brand_prob"                            
# [243] "orderTimeDoW_brand_Twice"                            "orderTimeDoW_categoryIDs_nUser"                     
# [245] "orderTimeDoW_categoryIDs_nUserUsed"                  "orderTimeDoW_categoryIDs_prob"                      
# [247] "orderTimeDoW_categoryIDs_Twice"                      "orderTimeDoW_nUser"                                 
# [249] "orderTimeDoW_nUserUsed"                              "orderTimeDoW_premiumProduct_nUser"                  
# [251] "orderTimeDoW_premiumProduct_nUserUsed"               "orderTimeDoW_premiumProduct_prob"                   
# [253] "orderTimeDoW_price_nUser"                            "orderTimeDoW_price_nUserUsed"                       
# [255] "orderTimeDoW_price_prob"                             "orderTimeDoW_price_Twice"                           
# [257] "orderTimeDoW_prob"                                   "orderTimeDoW_productGroup_nUser"                    
# [259] "orderTimeDoW_productGroup_nUserUsed"                 "orderTimeDoW_productGroup_prob"                     
# [261] "orderTimeDoW_productGroup_Twice"                     "orderTimeDoW_ratio_bp_p_round_nUser"                
# [263] "orderTimeDoW_ratio_bp_p_round_nUserUsed"             "orderTimeDoW_ratio_bp_p_round_prob"                 
# [265] "orderTimeDoW_ratio_bp_p_round_Twice"                 "orderTimeDoW_TimeBtwnRecOrder_disc_nUser"           
# [267] "orderTimeDoW_TimeBtwnRecOrder_disc_nUserUsed"        "orderTimeDoW_TimeBtwnRecOrder_disc_prob"            
# [269] "orderTimeDoW_TimeBtwnRecOrder_disc_Twice"            "orderTimeTime_basePrice_nUser"                      
# [271] "orderTimeTime_basePrice_nUserUsed"                   "orderTimeTime_basePrice_prob"                       
# [273] "orderTimeTime_basePrice_Twice"                       "orderTimeTime_brand_nUser"                          
# [275] "orderTimeTime_brand_nUserUsed"                       "orderTimeTime_brand_prob"                           
# [277] "orderTimeTime_brand_Twice"                           "orderTimeTime_categoryIDs_nUser"                    
# [279] "orderTimeTime_categoryIDs_nUserUsed"                 "orderTimeTime_categoryIDs_prob"                     
# [281] "orderTimeTime_categoryIDs_Twice"                     "orderTimeTime_nUser"                                
# [283] "orderTimeTime_nUserUsed"                             "orderTimeTime_orderTimeDoW_nUser"                   
# [285] "orderTimeTime_orderTimeDoW_nUserUsed"                "orderTimeTime_orderTimeDoW_prob"                    
# [287] "orderTimeTime_orderTimeDoW_Twice"                    "orderTimeTime_premiumProduct_nUser"                 
# [289] "orderTimeTime_premiumProduct_nUserUsed"              "orderTimeTime_premiumProduct_prob"                  
# [291] "orderTimeTime_premiumProduct_Twice"                  "orderTimeTime_price_nUser"                          
# [293] "orderTimeTime_price_nUserUsed"                       "orderTimeTime_price_prob"                           
# [295] "orderTimeTime_price_Twice"                           "orderTimeTime_prob"                                 
# [297] "orderTimeTime_productGroup_nUser"                    "orderTimeTime_productGroup_nUserUsed"               
# [299] "orderTimeTime_productGroup_prob"                     "orderTimeTime_productGroup_Twice"                   
# [301] "orderTimeTime_ratio_bp_p_round_nUser"                "orderTimeTime_ratio_bp_p_round_nUserUsed"           
# [303] "orderTimeTime_ratio_bp_p_round_prob"                 "orderTimeTime_ratio_bp_p_round_Twice"               
# [305] "orderTimeTime_TimeBtwnRecOrder_disc_nUser"           "orderTimeTime_TimeBtwnRecOrder_disc_nUserUsed"      
# [307] "orderTimeTime_TimeBtwnRecOrder_disc_prob"            "orderTimeTime_TimeBtwnRecOrder_disc_Twice"          
# [309] "orderTimeTime_Twice"                                 "price_basePrice_nUser"                              
# [311] "price_basePrice_nUserUsed"                           "price_basePrice_prob"                               
# [313] "price_basePrice_Twice"                               "price_brand_nUser"                                  
# [315] "price_brand_nUserUsed"                               "price_brand_prob"                                   
# [317] "price_brand_Twice"                                   "price_categoryIDs_nUser"                            
# [319] "price_categoryIDs_nUserUsed"                         "price_categoryIDs_prob"                             
# [321] "price_categoryIDs_Twice"                             "price_nUser"                                        
# [323] "price_nUserUsed"                                     "price_premiumProduct_nUser"                         
# [325] "price_premiumProduct_nUserUsed"                      "price_premiumProduct_prob"                          
# [327] "price_premiumProduct_Twice"                          "price_prob"                                         
# [329] "price_productGroup_nUser"                            "price_productGroup_nUserUsed"                       
# [331] "price_productGroup_prob"                             "price_productGroup_Twice"                           
# [333] "price_ratio_bp_p_round_nUser"                        "price_ratio_bp_p_round_nUserUsed"                   
# [335] "price_ratio_bp_p_round_prob"                         "price_ratio_bp_p_round_Twice"                       
# [337] "price_Twice"                                         "productGroup_brand_nUser"                           
# [339] "productGroup_brand_nUserUsed"                        "productGroup_brand_prob"                            
# [341] "productGroup_brand_Twice"                            "productGroup_categoryIDs_nUser"                     
# [343] "productGroup_categoryIDs_nUserUsed"                  "productGroup_categoryIDs_prob"                      
# [345] "productGroup_categoryIDs_Twice"                      "productGroup_nUser"                                 
# [347] "productGroup_nUserUsed"                              "productGroup_premiumProduct_nUser"                  
# [349] "productGroup_premiumProduct_nUserUsed"               "productGroup_premiumProduct_prob"                   
# [351] "productGroup_premiumProduct_Twice"                   "productGroup_prob"                                  
# [353] "productGroup_ratio_bp_p_round_nUser"                 "productGroup_ratio_bp_p_round_nUserUsed"            
# [355] "productGroup_ratio_bp_p_round_prob"                  "productGroup_ratio_bp_p_round_Twice"                
# [357] "productGroup_Twice"                                  "ratio_bp_p.y"                                       
# [359] "ratio_bp_p_round"                                    "ratio_bp_p_round_brand_nUser"                       
# [361] "ratio_bp_p_round_brand_nUserUsed"                    "ratio_bp_p_round_brand_prob"                        
# [363] "ratio_bp_p_round_brand_Twice"                        "ratio_bp_p_round_nUser"                             
# [365] "ratio_bp_p_round_nUserUsed"                          "ratio_bp_p_round_premiumProduct_nUser"              
# [367] "ratio_bp_p_round_premiumProduct_nUserUsed"           "ratio_bp_p_round_premiumProduct_prob"               
# [369] "ratio_bp_p_round_premiumProduct_Twice"               "ratio_bp_p_round_prob"                              
# [371] "ratio_bp_p_round_Twice"                              "reward_basePrice_nUser"                             
# [373] "reward_basePrice_nUserUsed"                          "reward_basePrice_prob"                              
# [375] "reward_basePrice_Twice"                              "reward_brand_nUser"                                 
# [377] "reward_brand_nUserUsed"                              "reward_brand_prob"                                  
# [379] "reward_brand_Twice"                                  "reward_categoryIDs_nUser"                           
# [381] "reward_categoryIDs_nUserUsed"                        "reward_categoryIDs_prob"                            
# [383] "reward_categoryIDs_Twice"                            "reward_couponsReceivedDoW_nUser"                    
# [385] "reward_couponsReceivedDoW_nUserUsed"                 "reward_couponsReceivedDoW_prob"                     
# [387] "reward_couponsReceivedDoW_Twice"                     "reward_couponsReceivedTime_nUser"                   
# [389] "reward_couponsReceivedTime_nUserUsed"                "reward_couponsReceivedTime_prob"                    
# [391] "reward_couponsReceivedTime_Twice"                    "reward_orderTimeDoW_nUser"                          
# [393] "reward_orderTimeDoW_nUserUsed"                       "reward_orderTimeDoW_prob"                           
# [395] "reward_orderTimeDoW_Twice"                           "reward_orderTimeTime_nUser"                         
# [397] "reward_orderTimeTime_nUserUsed"                      "reward_orderTimeTime_prob"                          
# [399] "reward_orderTimeTime_Twice"                          "reward_premiumProduct_nUser"                        
# [401] "reward_premiumProduct_nUserUsed"                     "reward_premiumProduct_prob"                         
# [403] "reward_premiumProduct_Twice"                         "reward_price_nUser"                                 
# [405] "reward_price_nUserUsed"                              "reward_price_prob"                                  
# [407] "reward_price_Twice"                                  "reward_productGroup_nUser"                          
# [409] "reward_productGroup_nUserUsed"                       "reward_productGroup_prob"                           
# [411] "reward_productGroup_Twice"                           "reward_ratio_bp_p_round_nUser"                      
# [413] "reward_ratio_bp_p_round_nUserUsed"                   "reward_ratio_bp_p_round_prob"                       
# [415] "reward_ratio_bp_p_round_Twice"                       "reward_TimeBtwnRecOrder_disc_nUser"                 
# [417] "reward_TimeBtwnRecOrder_disc_nUserUsed"              "reward_TimeBtwnRecOrder_disc_prob"                  
# [419] "reward_TimeBtwnRecOrder_disc_Twice"                  "TimeBtwnRecOrder_disc"                              
# [421] "TimeBtwnRecOrder_disc_basePrice_nUser"               "TimeBtwnRecOrder_disc_basePrice_nUserUsed"          
# [423] "TimeBtwnRecOrder_disc_basePrice_prob"                "TimeBtwnRecOrder_disc_basePrice_Twice"              
# [425] "TimeBtwnRecOrder_disc_brand_nUser"                   "TimeBtwnRecOrder_disc_brand_nUserUsed"              
# [427] "TimeBtwnRecOrder_disc_brand_prob"                    "TimeBtwnRecOrder_disc_brand_Twice"                  
# [429] "TimeBtwnRecOrder_disc_categoryIDs_nUser"             "TimeBtwnRecOrder_disc_categoryIDs_nUserUsed"        
# [431] "TimeBtwnRecOrder_disc_categoryIDs_prob"              "TimeBtwnRecOrder_disc_categoryIDs_Twice"            
# [433] "TimeBtwnRecOrder_disc_nUser"                         "TimeBtwnRecOrder_disc_nUserUsed"                    
# [435] "TimeBtwnRecOrder_disc_premiumProduct_nUser"          "TimeBtwnRecOrder_disc_premiumProduct_nUserUsed"     
# [437] "TimeBtwnRecOrder_disc_premiumProduct_prob"           "TimeBtwnRecOrder_disc_premiumProduct_Twice"         
# [439] "TimeBtwnRecOrder_disc_price_nUser"                   "TimeBtwnRecOrder_disc_price_nUserUsed"              
# [441] "TimeBtwnRecOrder_disc_price_prob"                    "TimeBtwnRecOrder_disc_price_Twice"                  
# [443] "TimeBtwnRecOrder_disc_prob"                          "TimeBtwnRecOrder_disc_productGroup_nUser"           
# [445] "TimeBtwnRecOrder_disc_productGroup_nUserUsed"        "TimeBtwnRecOrder_disc_productGroup_prob"            
# [447] "TimeBtwnRecOrder_disc_productGroup_Twice"            "TimeBtwnRecOrder_disc_ratio_bp_p_round_nUser"       
# [449] "TimeBtwnRecOrder_disc_ratio_bp_p_round_nUserUsed"    "TimeBtwnRecOrder_disc_ratio_bp_p_round_prob"        
# [475] "TimeBtwnRecOrder_disc_ratio_bp_p_round_Twice"        

# [938] "weichengProb"                                       
 

```




