---
title: Curation and Cross Validation to Reduce Features
titleshort: Too many features
instructions: 
output:
  usefulR::DMC_format
---

<!--- # (R code (No Results in Document)) -->
```{r set-parent, echo=FALSE,warning=FALSE,error=FALSE,message=FALSE,cache=TRUE,warning=FALSE,include=FALSE,comment=NA}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "/Users/user/dmc2015/predictions"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("/Users/user/dmc2015/predictions/combine_preds.rmd")
```

I am using the following packages:
<!--- # (R code (No Results in Document))-->
```{r paks, echo=TRUE, cache=FALSE, message=FALSE, tidy=FALSE, include=TRUE}
   library(magrittr)
   library(dplyr)
   library(reshape2)
   library(tidyr)
   library(lubridate)
   library(ggplot2)
   library(directlabels)
   library(rCharts)
   library(xtable)
   library(foreach)
   library(gtools)
   library(knitr)
   library(utils)
   library(GGally)
   source("~/dmc2015/ian/R/renm.R")
```

<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   predPlot = function(pred_set1,pred_set2){
     p = qplot(pred_set1,pred_set2) + coord_fixed() + geom_abline(intercept=0,slope=1,color="red")
     print(p)
     return(p)
   }

   lossFunction = function(pred,actual) sum(((1/mean(actual))*(pred - actual))^2)

   predictor_weight = function(pred1,pred2,actual){
      alphas = seq(0,1,.001)
      err = sapply(alphas, function(alpha) lossFunction(alpha*pred1 + (1-alpha)*pred2, actual))
      pred = data.frame(proportion.1 = alphas, err = err)
      return(pred)
   }
```
My working directory is set to \verb!~/dmc2015/predictions/!.

I am using our new clean data - so should you
<!--- chunk-label: R code (No Results in Document) -->
```{r cache=FALSE}
   source("~/dmc2015/ian/load_data.r")
   HTVset1 = readRDS("~/dmc2015/data/featureMatrix/HTVset1.rds")
   actual.val = as.vector(t(HTVset1$V[,c("coupon1Used","coupon2Used","coupon3Used")]))

   HTVset3 = readRDS("~/dmc2015/data/featureMatrix/HTVset3.rds")
   actual.val = as.vector(t(HTVset3$V[,c("coupon1Used","coupon2Used","coupon3Used")]))
```

##Reading in the predictions

<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   files = list.files("~/dmc2015/predictions/",pattern="rds")
   files
```


##Prediction Geometry
<!--- chunk-label: R code (No Results in Document) -->
```{r chunk-label,cache=FALSE}
   preds = lapply(files,function(x) readRDS(x))

   predPlot(preds[[1]]$validation$prediction, preds[[2]]$validation$prediction)

   wgthd = predictor_weight(preds[[1]]$validation$prediction, preds[[2]]$validation$prediction, actual.val)

   head(wgthd)
   qplot(proportion.1,err,data=wgthd)

   sapply(1:length(files), function(i) names(preds[[i]]))
```
