---
title: Feature Matrix Version 0.4
titleshort: FMat 0.4
instructions: 
output:
  usefulR::DMC_format
---

<!--- # (R code (No Results in Document)) -->
```{r set-parent, echo=FALSE,warning=FALSE,error=FALSE,message=FALSE,cache=TRUE,warning=FALSE,include=FALSE,comment=NA}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "/Users/user/dmc2015/features/feature_files/R"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("/Users/user/dmc2015/features/feature_files/R/create_feature_matrix_version0.4.rmd")
```

I am using the following packages:
<!--- # (R code (No Results in Document))-->
```{r paks, echo=TRUE, cache=FALSE, message=FALSE, tidy=FALSE, include=TRUE}
   library(magrittr)
   library(dplyr)
   library(tidyr)
   library(lubridate)
   library(ggplot2)
   library(rCharts)
   library(xtable)
   library(foreach)
   library(gtools)
   library(knitr)
   library(utils)
   source("~/dmc2015/ian/R/renm.R")
```

# Adding new features
<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   fmat = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_WIDE_ver0.3.rds")
   HTV = readRDS("~/dmc2015/data/featureMatrix/HTVset1.rds")

   ## data
   source("~/dmc2015/ian/universal_clean_data.r")
   d.list = universal_clean_data()
   d = d.list$d
   dm = d.list$dm
   dmc = d.list$dmc
   
   #new features
   files = list.files("../set1/new_llrs",full.names=TRUE)
```

<!--- chunk-label: R code (No Results in Document) -->
```{r cache=FALSE}
   #previous features
   fml = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_LONG_ver0.3.rds")

   long.files = files[grep("long",files)]
   featureslong = lapply(long.files, function(x) readRDS(x))

   fml$train$X = fml$train$X[,!(grepl("timesNotUsed", names(fml$train$X)) | grepl("timesUsed",names(fml$train$X)) | grepl("ntimes",names(fml$train$X)))]
   fml$validation$X = fml$validation$X[,!(grepl("timesNotUsed", names(fml$validation$X)) | grepl("timesUsed",names(fml$validation$X)) | grepl("ntimes",names(fml$validation$X)))]
   fml$class$X = fml$class$X[,!(grepl("timesNotUsed", names(fml$class$X)) | grepl("timesUsed",names(fml$class$X)) | grepl("ntimes",names(fml$class$X)))]

   for(i in 1:106){
      cat(i,"\n")
      features = featureslong[[i]]
      features$couponCol = as.numeric(features$couponCol) 
      features = features[,!(grepl("timesNotUsed",names(features)) | grepl("timesUsed",names(features)) | grepl("ntimes",names(features)))]
      fml$train$X = fml$train$X %>% left_join(features,by=c("orderID","couponCol"))
      fml$validation$X = fml$validation$X %>% left_join(features,by=c("orderID","couponCol"))
      fml$class$X = fml$class$X %>% left_join(features,by=c("orderID","couponCol"))
   }
```

<!--- chunk-label: R code (No Results in Document) -->
```{r cache=FALSE}
   fmw = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_WIDE_ver0.3.rds")
   wide.files = files[grep("wide",files)]
   featureswide = lapply(wide.files, function(x) readRDS(x))

   fmw$train$X = fmw$train$X[,!(grepl("timesNotUsed", names(fmw$train$X)) | grepl("timesUsed",names(fmw$train$X)) | grepl("ntimes",names(fmw$train$X)))]
   fmw$validation$X = fmw$validation$X[,!(grepl("timesNotUsed", names(fmw$validation$X)) | grepl("timesUsed",names(fmw$validation$X)) | grepl("ntimes",names(fmw$validation$X)))]
   fmw$class$X = fmw$class$X[,!(grepl("timesNotUsed", names(fmw$class$X)) | grepl("timesUsed",names(fmw$class$X)) | grepl("ntimes",names(fmw$class$X)))]
   
   for(i in 1:length(wide.files)){
      cat(i,"\n")
      features = featureswide[[i]]
      features = features[,!(grepl("timesNotUsed",names(features)) | grepl("timesUsed",names(features)) | grepl("ntimes",names(features)))]
      fmw$train$X = fmw$train$X %>% left_join(features,by=c("orderID"))
      fmw$validation$X = fmw$validation$X %>% left_join(features,by=c("orderID"))
      fmw$class$X = fmw$class$X %>% left_join(features,by=c("orderID"))
   }
```

## save them
```{r cache=FALSE}
   saveRDS(fml,"~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_LONG_ver0.4.rds")

   saveRDS(fmw,"~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_WIDE_ver0.4.rds")
```
