---
title: Checking the log-likelihood ratio statistics
titleshort: Checking Multiway LLR
instructions: 
author: Ian Mouzon
authorshort: imouzon
contact: imouzon@iastate.edu
grouplong: Iowa State University's 2015 Data Mining Cup Team
groupshort: DMC@ISU
leader: One Week Left 
leadershort: One Week Left
semester: Spring 2015
assignment: 
duedate: May 13, 2015
output:
  usefulR::hw_format
---

<!--- # (R code (No Results in Document)) -->
```{r set-parent, echo=FALSE,warning=FALSE,error=FALSE,message=FALSE,cache=TRUE,warning=FALSE,include=FALSE,comment=NA}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "/Users/user/dmc2015/ian"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("/Users/user/dmc2015/ian/3way_llr.rmd")
```

I am using the following packages:
<!--- # (R code (No Results in Document))-->
```{r paks, echo=TRUE, cache=FALSE, message=FALSE, tidy=FALSE, include=TRUE}
   library(magrittr)
   library(dplyr)
   library(tidyr)
   library(lubridate)
   library(ggplot2)
   library(rCharts)
   library(xtable)
   library(foreach)
   library(gtools)
   library(knitr)
   library(utils)
   source("~/dmc2015/ian/R/renm.R")
```

# Getting Tranthe Data and Manipulations 
I am using our new clean data - so should you
<!--- chunk-label: R code (No Results in Document) -->
```{r cache=FALSE}
   d = readRDS("../data/clean_data/universalCleanData.rds")

   source("./R/clean_factor.r")
   d = clean_factor(d,"couponID","cpn")
   d = clean_factor(d,"brand","brand")
   d = clean_factor(d,"productGroup","prod")
   d = clean_factor(d,"categoryIDs")
```

I can melt the columns by coupon using the following:
<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   source("./r/stackCoupons2.R")
   dm = stackCoupons2(d,idcols = c(1:4,32:49)) 
```

## Make a few quick features
<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   dm$ShopFast = 1*(dm$TimeBtwnRecOrder < 28)
   dm$EarlyRec = 1*(dm$TimeBtwnSentRec < 8)

   dm$Shop60 = floor(dm$orderTimeTime)
   dm$Shop30 = floor(dm$orderTimeTime * 60/30)*30/60
   dm$Shop15 = floor(dm$orderTimeTime * 60/15)*15/60

   dm$RecExpire60 = floor(dm$TimeBtwnSentRec)
   dm$RecOrder60 = floor(dm$TimeBtwnRecOrder)
   dm$OrderExpire60 = floor(dm$TimeBtwnOrderExpire)
   dm$basePrice_price_ratio = dm$basePrice/dm$price
```

I and can split the columns of product group using:
<!--- splitcols: R code (No Results in Document) -->
```{r splitcols,cache=FALSE}
   source("./r/splitColumn.R")
   dmc = splitColumn(dm,"categoryIDs","orderID",splitby=":") 
   dmc = dmc[,-which(names(dmc) == "categoryIDs")]
   dmc = clean_factor(dmc,"categoryIDs",scrape_off="cat")
   dmc = dm %>% 
      left_join(dmc %>%
            select(orderID,couponCol,categoryIDs1, categoryIDs2, ca;qtegoryIDs3, categoryIDs4, categoryIDs5) %>%
            gather(tmp,categoryID,-orderID,-couponCol) %>%
            mutate(categoryEntry = gsub("categoryIDs","",tmp)) %>%
            select(orderID,couponCol,categoryEntry,categoryID) %>%
            arrange(orderID,couponCol,categoryEntry) %>%
            filter(!is.na(categoryID)),
         by = c("orderID","couponCol")) %>%
      arrange(orderID,couponCol,categoryEntry)
```
We can also get the HTV set.
<!--- chunk-label: R code (No Results in Document) -->
```{r chunk-label,cache=FALSE}
   HTVset1 = readRDS("~/dmc2015/data/featureMatrix/HTVset1.rds")
   trn = dm[which(dm$orderID %in% HTVset1$T$orderID),]
   val = dm[which(dm$orderID %in% HTVset1$V$orderID),]
   cls = dm[which(dm$orderID %in% HTVset1$C$orderID),]
```

# A Mini-Feature Matrix
<!--- : R code (No Results in Document) -->
```{r cache=FALSE}
   files = list.files("~/dmc2015/features/feature_files/set1/",full.names=TRUE,pattern="llr") 
   files = files[grepl("long",files)]

   features = lapply(files,function(x) readRDS(x))
   features = lapply(1:length(features),function(x) features[[x]][,c(1,2,6)])

   fmt = trn[,c("orderID","couponUsed","couponCol")]
   for(i in 1:length(features)) fmt = fmt %>% left_join(features[[i]],by=c("orderID","couponCol"))

   fmv = val[,c("orderID","couponCol")]
   for(i in 1:length(features)) fmv = fmv %>% left_join(features[[i]],by=c("orderID","couponCol"))

   names(fmv
   cor(fmv[,1:4])
   cor = cor(fmv[,-(1:2)])
   features[[9]][1:5,1:3]
   llr_naive_basePrice_price_ratio
   cor(fmv[,3:5])
```
