---
title: Reducing the features
titleshort: Too many features
instructions: 
author: Ian Mouzon
authorshort: imouzon
contact: imouzon@iastate.edu
grouplong: Iowa State University's 2015 Data Mining Cup Team
groupshort: DMC@ISU
leader: One Week Left 
leadershort: One Week Left
semester: Spring 2015
assignment: 
duedate: May 13, 2015
output:
  usefulR::hw_format
---


<!--- # (R code (No Results in Document)) -->
```{r set-parent, echo=FALSE,warning=FALSE,error=FALSE,message=FALSE,cache=TRUE,warning=FALSE,include=FALSE,comment=NA}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "/Users/user/dmc2015/ian"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("/Users/user/dmc2015/ian/examining_features.rmd")
```

I am using the following packages:
<!--- # (R code (No Results in Document))-->
```{r paks, echo=TRUE, cache=FALSE, message=FALSE, tidy=FALSE, include=TRUE}
   library(magrittr)
   library(dplyr)
   library(reshape2)
   library(tidyr)
   library(lubridate)
   library(ggplot2)
   library(rCharts)
   library(xtable)
   library(foreach)
   library(gtools)
   library(knitr)
   library(utils)
   source("~/dmc2015/ian/R/renm.R")
```


# Load feature matrix
<!--- dgg: R code (No Results in Document) -->
```{r dgg,cache=FALSE}
   f1 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_LONG_ver0.2.rds")
   f2 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset2_LONG_ver0.2.rds")
   f3 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset3_LONG_ver0.2.rds")

   d1 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset1_WIDE_ver0.2.rds")
   d2 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset2_WIDE_ver0.2.rds")
   d3 = readRDS("~/dmc2015/data/featureMatrix/featMat_based-on-HTVset3_WIDE_ver0.2.rds")
```

# Check the data
<!--- chkh: R code (No Results in Document) -->
```{r chkh,cache=FALSE}
   Xn = f1$train$X
   
   #remove the naive columns
   Xn = Xn[,!grepl("naive",names(Xn))]

   Xv = f1$validation$X
   y = f1$validation$y$couponUsed
```

<!--- rf: R code (No Results in Document) -->
```{r rf,cache=FALSE}
   library(randomForest)

   Xrf = Xn[,c(3,grep("sim_", names(Xn)))]

   names(Xrf)
   rf_cpn = randomForest(Xrf, y=f1$train$y$couponUsed,  ntree=1000, mtry=4, replace=TRUE, keep.forest = TRUE, maxnodes = 50)

   ## print
   print(rf_cpn)

   ## plots
   varImpPlot(rf_cpn)
   qplot(Xrf[,16],Xrf[,15],color= rf_cpn$predicted)
   qplot(Xrf$order_match_class,rf_cpn$predicted,geom="boxplot",fill=as.factor(f1$train$y$couponUsed))
   #write.csv(matrix(c(Xn$orderID, rf_cpn$predicted),ncol=2),row.names=FALSE,quote=FALSE,file="./written_data/rf_prediction.csv")

   d1$validation$y %>% select(orderID,coupon1Used,coupon2Used,coupon3Used,basketValue)
   mutate(couponCol = rep(1:3,nrow(f1$validation$y)/3)) %>%
      mutate(pred = predict(rf_cpn,newdata=Xv[,c(3,grep("sim_", names(Xv)))]), err = (couponUsed - pred)^2) %>%
      group_by(couponCol) %>%
      summarize(errnum = sum(err), meansq = mean(couponCol)^2) %>% with(sum(errnum/meansq))

   names(f1$train$X)

   rf_bval = randomForest(Xrf, y=f1$train$y$basketValue,  ntree=1000, mtry=10, replace=TRUE, keep.forest = TRUE, maxnodes = 100)
   print(rfmod)
   keepercols = names(Xn[,17:20])
   dropercols = names(Xn[,c(13:16,21:30)])
```


