---
title: basePrice Over price
titleshort: price/basePrice
instructions:
author: Ian Mouzon
authorshort: imouzon
contact: imouzon@iastate.edu
grouplong: Iowa State University Team
groupshort: Data Mining Cup
leader: Feature Matrix Creation
leadershort: FMC
semester: Spring 2015
assignment: 
duedate: 
output:
  usefulR::hw_format
---

<!--- # (R code (No Results in Document)) -->
```{r set-parent, echo=FALSE,warning=FALSE,error=FALSE,message=FALSE,cache=TRUE,warning=FALSE,include=FALSE,comment=NA}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "/Users/user/dmc2015/ian"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("/Users/user/dmc2015/ian/Lihua_and_Ian_price-basePrice.rmd")
```

I am using the following packages:
<!--- # (R code (No Results in Document))-->
```{r paks, echo=TRUE, cache=FALSE, message=FALSE, tidy=FALSE, include=TRUE}
   library(ggplot2)
   library(lubridate)
   library(xtable)
   library(foreach)
   library(rCharts)
   library(magrittr)
   library(tidyr)
   library(dplyr)
   library(reshape2)
   library(gtools)
   library(sqldf)
   library(missForest)
   source("./R/renm.R")
```
and our working directory is set to \verb!dmc2015/ian!.

<!--- simpstats: R code (No Results in Document) -->
```{r simpstats,echo=FALSE,include=FALSE,message=FALSE,cache=FALSE}
   #set up knitr
   #devtools::install_github('imouzon/usefulR')
   library(usefulR)

   #set working directory
   working.dir = "~/dmc2015/ian"
   setwd(working.dir)

   #compile the document to PDF
   if(FALSE) 
      rmarkdown::render("./categorical_similarity.Rmd")
```

**Getting the Data and Manipulations**

I am using our new clean data - so should you
<!--- chunk-label: R code (No Results in Document) -->
```{r cache=FALSE,tidy=FALSE}
   d = readRDS("~/dmc2015/data/clean_data/universalCleanData.rds")
```

I can melt the columns by coupon using the following:
<!--- : R code (No Results in Document) -->
```{r cache=FALSE,message=FALSE}
   source("~/dmc2015/ian/r/stackCoupons2.R")
   dm = stackCoupons2(d,idcols = c(1:4,32:49))
```

I and can split the columns of product group using:
<!--- splitcols: R code (No Results in Document) -->
```{r splitcols,cache=FALSE}
   source("~/dmc2015/ian/r/splitColumn.R")
   dmc = splitColumn(dm,"categoryIDs","orderID",splitby=":") 
```

# A few simple statistics

**The ratio of price to basePrice**
<!--- f: R code (No Results in Document) -->
```{r famiy,cache=FALSE}
   ratios = dmc %>% 
      mutate(bPr2pr_ratio = basePrice/price,
             colname1 = paste0("bPr2pr_ratio",couponCol),
             bPr2pr_approx_ratio = round(bPr2pr_ratio,1),
             colname2 = paste0("bPr2pr_approx_ratio",couponCol)
      ) %>%
      select(orderID,colname1,bPr2pr_ratio,colname2,bPr2pr_approx_ratio) %>%
      arrange(orderID,colname1) %>%
      spread(colname1,bPr2pr_ratio) %>%
      arrange(orderID,colname2) %>%
      spread(colname2,bPr2pr_approx_ratio) %>%
      data.frame %>%
      saveRDS(file="~/dmc2015/features/feature_files/universal/basePrice_price_ratio.rds")
```
